### ISSUE TITLE
review on 2015-04-09

### ISSUE THREAD

**Issue by yiminghe** [shepherdwind/rc-dropzone#1]
功能确实很高级，好多 api 以前从没用过 :+1: 
- readme.md 格式不对，样式乱了，需要升级下 rc-server, rc-tools, generator-rc 到新版，去除了很多文件，可以对比下 https://github.com/react-component/calendar
- flux 是否适合细粒度的组件开发有待思考，store 存放了不同实例的数据，组件不内聚了
- 样式名要以 rc-dropzone 开头，统一到 rc 命名空间，可以考虑支持 prefixCls
- js 不要 require css，由应用者自己 require，方便换肤
- 可以在根目录建个自己的 server 用于 example 的上传测试

``` js
var app = require('rc-server')();
app.use(upload());
var port = 8000;
app.listen(port);
```
- 支持浏览器配置 https://github.com/react-component/rc-tools/issues/1
### 细节点 review 供参考：

https://github.com/shepherdwind/rc-dropzone/commit/770dda5b97a6a17732a545b0d7fa506c13817872

https://github.com/shepherdwind/rc-dropzone/commit/2d7061eba3c2b9e81b7840d0e2ea522aad937c30

**Comment by shepherdwind** [comment]
好的，这些我都改下。
